### ISSUE TITLE
WUI-search reports no results although Alerts were found

### ISSUE THREAD

**Issue by aremai** [ossec/ossec-wui#11]
I cloned ossec-wui from the repo and installed it on CentOS 6.6 with Apache 2.2 (latest version from the centos repo).
I followed the instructions in the README.

Yet, I get this error:
Results:
Total alerts found: 33
Nothing returned (or search expired). 

In the http_error log I find dozens of these:
PHP Warning:  fopen(./tmp/output-tmp.1-57-8cd5679a49c37a4583dfa34473436ab4.php): failed to open stream: No such file or directory in /var/www/html/ossec-wui/lib/os_lib_alerts.php on line 39

there's no tmp dir in /var/www/html/ossec-wui

the owner/group and perma of the /var/ossec/tmp dir however are:
root:apache and 770

selinux is disabled (set to permissive)

the temp file doesn't exist, nor does the tmp directory in the ossec-wui directory exist.
the whole ossec-wui directory (and its subdirectories) belong to root:root instead of apache:apache
maybe this is the problem?

**Comment by aremai** [comment]
i still have this problem.....
any ideas? it's *very* frustrating :(

**Comment by ddpbsd** [comment]
On Sep 16, 2015 6:16 PM, "theresa" <notifications@github.com> wrote:
>
> i still have this problem.....
> any ideas? it's very frustrating :(
>

Did you try creating the tmp directory? Or try to track down where the temp
file was being created and adding aome debugging to try and find out why?

**Comment by aremai** [comment]
Dan, as always you're the hero!!
the tmp directory was there, but for some reason it wasn't owned by the apache user. bit crazy, because I know I fixed that in the past.

anyway, thanks again for the pro-tip :) (i will now close this issue)
