### ISSUE TITLE
 Unable to include file: 'ossec_conf.php'. 

### ISSUE THREAD

**Issue by tenkorang** [ossec/ossec-wui#19]
I am trying to install Ossec UI on a Cent OS. After the intsallation, i get an interface that reads,  

 Unable to include file: 'ossec_conf.php'.
Internal error. Try again later. 

Kindly help me resolve this
![ossec](https://user-images.githubusercontent.com/31772978/30220754-20d49b00-94b0-11e7-9397-73984fcf2f01.JPG)

**Comment by ddpbsd** [comment]
This project is no longer maintained, so support might be sparse. Make sure the file is present, make aure the permissions make sense, check for additional errors in your webserver logs

**Comment by tenkorang** [comment]
thanks, it really worked
